[package]
name = "node-lcs-img-diff"
version = "0.1.0"
authors = ["bokuweb"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.50"
serde_derive = "1.0.21"
serde = "1.0.21"
serde_json = "1.0.6"
image = "0.19.0"