defaults: &defaults
  working_directory: ~/lcs-img-diff
  docker:
    - image: rust:latest
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout  
      - run:
          name: Install
          command: |
            apt-get update
            apt-get install nodejs npm -y
            rustup toolchain install nightly
            rustup target add wasm32-unknown-unknown --toolchain nightly
            npm i
            cargo +nightly install wasm-bindgen-cli            
      - run:
          name: Build
          command: |
            make build
            npm t   
