defaults: &defaults
  working_directory: ~/lcs-img-diff
  docker:
    - image: node
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout  
      - run:
          name: Test
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && \
            PATH="$HOME/.cargo/bin:$PATH" rustup install stable && \
            PATH="$HOME//.cargo/bin:$PATH" rustup install nightly
            npm i
            make build
            npm t   
