defaults: &defaults
  working_directory: ~/lcs-img-diff
  docker:
    - image: rust:latest
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout  
      - run:
          name: Install node
          command: |
            apt-get update
            apt-get install nodejs npm -y
      - run:
          name: Test
          command: |
            npm i
            cargo +nightly install wasm-bindgen-cli
            make build
            npm t   
