defaults: &defaults
  working_directory: ~/lcs-img-diff
  docker:
    - image: parity/rust:gitlab-ci
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout  
      - run:
          name: Test
          command: |
            npm i
            cargo +nightly install wasm-bindgen-cli
            make build
            npm t   
