defaults: &defaults
  working_directory: ~/lcs-img-diff
  docker:
    - image: rust
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout  
      - run:
          name: Test
          command: |
            wget http://nodejs.org/dist/v8.10.0/node-v8.10.0.tar.gz && \
            tar -zxvf node-v8.10.0.tar.gz && \
            cd node-v8.10.0 && ./configure && make && \
            make install
            npm i
            make build
            npm t   
